using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PC : MonoBehaviour
{
    public Life ネR;
    float 宥q;
    int 程j = 100;
    void Start()
    {
        宥q = 程j;
        ネR.宥qW(程j);
        DontDestroyOnLoad(this.gameObject);
    }
    public void ア(float 端`)
    {
        if (宥q > 0 && 宥q <= 程j)
        {
            宥q -= 端`;
            ネR.宥q逞l(宥q);
        }
    }
    public void 干(float 齑_)
    {
        if (宥q >= 0 && 宥q < 程j)
        {
            宥q += 齑_;
            ネR.宥q逞l(宥q);
        }
    }
    void OnCollisionEnter(Collision yH)
    {
        if (yH.gameObject.tag == "Hunter" && NPC.k瞒 == false)
        {
            ア(20);
            print(" ア ");
        }
    }
    void Update()
    {
        GetComponent<Rigidbody>().velocity = transform.TransformVector(0, GetComponent<Rigidbody>().velocity.y, Input.GetKey(KeyCode.W) ? 3 : Input.GetKey(KeyCode.S) ? -2 : 0);
        transform.Rotate(0, (Input.GetKey(KeyCode.A) ? -80 : Input.GetKey(KeyCode.D) ? 80 : 0) * Time.deltaTime, 0);
        GetComponent<Rigidbody>().AddForce(new Vector3(0, Input.GetKeyDown(KeyCode.Space) ? 3 : 0, 0), ForceMode.Impulse);
        if (transform.position.y < -1) transform.position = Vector3.up;
        if (NPC.k == true)
        {
            干(20);
            print(" 干 ");
        }
    }
}